# Generated by Django 2.0 on 2019-03-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ICD', '0002_auto_20190318_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icdsubcodes',
            name='icd_code',
            field=models.ForeignKey(blank=True, db_column='icd_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icd_sub_codes', to='ICD.ICDCodes'),
        ),
    ]
