# Generated by Django 2.0 on 2019-04-18 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ICD', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='DatabaseAdmin',
            fields=[
                ('da_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('country_code', models.ForeignKey(blank=True, db_column='country_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.Country')),
            ],
            options={
                'db_table': 'database_admin',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code', models.ForeignKey(blank=True, db_column='country_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.Country')),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
        migrations.CreateModel(
            name='MedicalPractitioner',
            fields=[
                ('mp_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dob', models.DateField(blank=True, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('clinic_address', models.TextField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, max_length=10, null=True)),
                ('field', models.TextField(blank=True, null=True)),
                ('country_code', models.ForeignKey(blank=True, db_column='country_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.Country')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.Hospital')),
            ],
            options={
                'db_table': 'medical_practitioner',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=5, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('contact_no_1', models.BigIntegerField(blank=True, null=True)),
                ('contact_no_2', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('dhx', models.TextField(blank=True, db_column='DHx', null=True)),
                ('ca', models.IntegerField(blank=True, db_column='Ca', null=True)),
                ('iddm', models.IntegerField(blank=True, db_column='IDDM', null=True)),
                ('niddm', models.IntegerField(blank=True, db_column='NIDDM', null=True)),
                ('mi', models.IntegerField(blank=True, db_column='MI', null=True)),
                ('af', models.IntegerField(blank=True, db_column='AF', null=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('country_code', models.ForeignKey(blank=True, db_column='country_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.Country')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='PatientCase',
            fields=[
                ('case_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('hpc', models.TextField(blank=True, db_column='HPC', null=True)),
                ('moi', models.TextField(blank=True, db_column='MoI', null=True)),
                ('d_and_v', models.TextField(blank=True, db_column='D_and_V', null=True)),
                ('clinical_note', models.TextField(blank=True, null=True)),
                ('no_of_visits', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('icd_code', models.ForeignKey(blank=True, db_column='icd_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ICD.ICDCodes')),
                ('icd_sub_code', models.ForeignKey(blank=True, db_column='icd_sub_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ICD.ICDSubCodes')),
                ('mp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.MedicalPractitioner')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_cases', to='Patient.Patient')),
            ],
            options={
                'db_table': 'patient_case',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('record_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('visit_no', models.BigIntegerField(blank=True, null=True)),
                ('on_arrival', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('tx', models.TextField(blank=True, db_column='Tx', null=True)),
                ('report_suggestions', models.TextField(blank=True, null=True)),
                ('medication', models.TextField(blank=True, null=True)),
                ('advice', models.TextField(blank=True, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_records', to='Patient.PatientCase')),
            ],
            options={
                'db_table': 'patient_record',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('pincode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_type', models.IntegerField(choices=[(1, 'Database-Admin'), (2, 'Medical-Practitioner')], default=None)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='pincode',
            field=models.ForeignKey(blank=True, db_column='pincode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.Region'),
        ),
        migrations.AddField(
            model_name='medicalpractitioner',
            name='pincode',
            field=models.ForeignKey(blank=True, db_column='pincode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.Region'),
        ),
        migrations.AddField(
            model_name='medicalpractitioner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_practitioner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pincode',
            field=models.ForeignKey(blank=True, db_column='pincode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.Region'),
        ),
        migrations.AddField(
            model_name='databaseadmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='database_admin_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
