# Generated by Django 2.0 on 2019-04-20 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalpractitioner',
            options={'permissions': (('add_patient', 'Can add patient'), ('delete_patient', 'Can delete patient'), ('change_patient', 'Can change patient'), ('add_patientcase', 'Can add patient case'), ('delete_patientcase', 'Can delete patient case'), ('change_patientcase', 'Can change patient case'), ('add_patientrecord', 'Can add patient record'), ('delete_patientrecord', 'Can delete patient record'), ('change_patientrecord', 'Can change patient record'))},
        ),
    ]
