# Generated by Django 2.0 on 2019-03-21 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalpractitioner',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='medical_practitioner_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
