# Generated by Django 2.0 on 2019-03-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_auto_20190318_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientcase',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='patientrecord',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='icd_code',
            field=models.ForeignKey(blank=True, db_column='icd_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ICD.ICDCodes'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='icd_sub_code',
            field=models.ForeignKey(blank=True, db_column='icd_sub_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ICD.ICDSubCodes'),
        ),
    ]
